# Generated by Django 4.1.5 on 2023-06-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ProfileImage',
            field=models.ImageField(blank=True, default='pp-female.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='56b7e6872d1f4892aae98800d65e73f3', editable=False, primary_key=True, serialize=False),
        ),
    ]
