# Generated by Django 4.1.5 on 2023-06-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_profileimage_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ProfileImage',
            field=models.ImageField(blank=True, default='pp-female.jpg', null=True, upload_to='<django.db.models.fields.UUIDField>/profile/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='5e7562e3cfd04ba5b8471f4a04eab01e', editable=False, primary_key=True, serialize=False),
        ),
    ]
