# Generated by Django 4.1.5 on 2023-06-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_customuser_profileimage_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('ID', models.UUIDField(default='af04c8f3390645f1841e9eb766b3576a', editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='648d66da08ab47bca4672922c78892f0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('ID', models.UUIDField(default='0a318812f541489bb85a90d47e59b515', editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('ProgrammeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('ID', models.UUIDField(default='6ffe68daadf643c3a01f78bc0f9e803f', editable=False, primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('Answer', models.CharField(max_length=20)),
                ('OptionOne', models.CharField(max_length=20)),
                ('OptionTwo', models.CharField(max_length=20)),
                ('OptionThree', models.CharField(max_length=20)),
                ('OptionFour', models.CharField(max_length=20)),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.subject')),
            ],
        ),
    ]
