# Generated by Django 4.1.5 on 2023-06-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_questions_options_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'verbose_name_plural': 'Programme'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subject'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default='a5d71f63786d411bb2fb7d3dc6963f77', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programme',
            name='ID',
            field=models.UUIDField(default='cb4766a7a1794226bdc59d073d44769c', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='ID',
            field=models.UUIDField(default='610f969c283a4a90aed36f795d690536', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='ID',
            field=models.UUIDField(default='2fd7ff7ade50453fa2596e73cdc7b494', editable=False, primary_key=True, serialize=False),
        ),
    ]
