# Generated by Django 4.2.2 on 2023-07-19 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_alter_results_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'FeedBack',
            },
        ),
    ]
