# Generated by Django 4.2.3 on 2023-08-16 08:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_feedback_ismarked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportQuestion',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Details', models.TextField()),
                ('Date', models.DateField(default=datetime.date.today, editable=False)),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.questions')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Report',
            },
        ),
    ]
