# Generated by Django 4.2.3 on 2023-08-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_reportquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportquestion',
            old_name='Details',
            new_name='Issue',
        ),
    ]
