# Generated by Django 4.2.3 on 2023-08-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_rename_details_reportquestion_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportquestion',
            name='IsMarked',
            field=models.BooleanField(default=False),
        ),
    ]
