# Generated by Django 4.2.3 on 2023-10-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_reportquestion_ismarked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportquestion',
            options={'verbose_name_plural': 'ReportQuestion'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='FullName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
