# Generated by Django 4.2.3 on 2023-12-04 05:22

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_alter_reportquestion_options_customuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='TestsTaken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to=Users.models.user_directory_path),
        ),
    ]
