# Generated by Django 4.2.3 on 2023-12-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_resultsextradetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='TestsTaken',
        ),
        migrations.AddField(
            model_name='resultsextradetails',
            name='BCA',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultsextradetails',
            name='BIM',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultsextradetails',
            name='BIT',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultsextradetails',
            name='BSCSIT',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultsextradetails',
            name='TestsTaken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
