# Generated by Django 4.2.3 on 2023-12-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_subject_totalquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='TotalQuestions',
            field=models.BigIntegerField(default=0),
        ),
    ]
