from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.GetUserLists, name='admin-index'),
    path('users/', views.GetUserLists, name='user-details'),
    path('profile/', views.UserProfile, name='user-profile'),
    path('history/', views.UserHistory, name='user-history'),
    path('user-search/', views.UserSearch, name='user-search'),
    path('feedbacks/', views.GetFeedbackLists, name='feedback'),
    path('users-search/', views.UserSearch, name='users-search'),
    path('reports/', views.GetReportsLists, name='report-lists'),
    path('exams/', views.GetUsersExamsLists, name='users-exams'),
    path('add-question/', views.AddQuestion, name='add-question'),
    path('users/edit/<str:id>', views.EditUsers, name="edit-user"),
    path('report-search/', views.ReportSearch, name='report-search'),
    path('report/<str:id>/mark', views.MarkReport, name="mark-report"),
    path('subject-search/', views.SubjectSearch, name='subject-search'),
    path('feedback-search/', views.FeedbackSearch, name='feedback-search'),
    path('question-search/', views.QuestionSearch, name='question-search'),
    path('feedback/<str:id>/mark', views.MarkFeedBack, name="mark-feedback"),
    path('programmes/', views.GetProgrammeLists, name='getProgrammeDetails'),
    path('report/edit-report/<str:id>', views.EditReports, name='edit-report'),
    path('questions/edit/<str:id>', views.EditQuestions, name="edit-question"),
    path('questions/', views.GetQuestionsProgrammes, name='questions-programmes'),
    path('users-exams-search/', views.UsersExamsSearch, name='users-exams-search'),
    path('subjects/', views.GetSubjectPrograms, name='subject-programmes-details'),
    path('subjects/<str:programme>', views.GetSubjectLists, name='subject-details'),
    path('report-question/<str:id>', views.ReportQuestions, name='report-question'),
    path('feedback/edit-feedback/<str:id>', views.EditFeedback, name='edit-feedback'),
    path('questions/edit/<str:id>/delete', views.DeleteQuestion, name="delete-question"),
    path('admin-change-password/', views.AdminChangePassword, name='admin-change-password'),
    path('detailed-exams-search/', views.DetailedExamsSearch, name='detailed-exams-search'),
    path('subjects/<str:programme>/<str:subject>/edit', views.EditSubject, name='edit-subject'),
    path('delete-account/<str:id>', views.DeleteAccountFromAdmin, name='delete-account-from-admin'),
    path('questions/<str:programme>', views.GetQuestionsPerProgram, name='questions-per-programme'),
    path('exams/<str:user_email>', views.GetUsersExamsProgrammeLists, name='users-exams-programmes'),
    path('question-programme-search/', views.QuestionProgrammeSearch, name='question-programme-search'),
    path('questions/<str:programme>/<str:subject>', views.GetQuestionLists, name='questions-per-subject'),
    path('users-exams-programme-search/', views.UsersExamsProgrammeSearch, name='users-exams-programme-search'),
    path('question-per-programme-search/', views.QuestionPerProgrammeSearch, name='question-per-programme-search'),
    path('exams/<str:user_email>/<str:programme>', views.GetDetailedExamsLists, name='users-exams-each-programme'),

    path('', views.Index, name='index'),
    path('login/', views.Login, name='login'),
    path('signup/', views.SignUp, name='signup'),
    path('logout/', views.Logout, name='logout'),
    path('result/', views.GetResult, name='get-result'),
    path('leaderboard/', views.LeaderBoard, name='leaderboard'),
    path('dashboard/', views.UserDashboard, name='user-dashboard'),
    path('delete-account/', views.DeleteAccount, name='delete-account'),
    path('update-profile/', views.UpdateProfile, name='update-profile'),
    path('model-test/<program>', views.TakeModelTest, name='model-test'),
    path('update-password/', views.UpdatePassword, name='update-password'),
    path('program-selector/', views.ProgramSelector, name='program-selector'),
    path('model-test/<str:programme>/<str:subject>', views.GetSpecificQuestions),
    path('detailed-result/<slug:slug>', views.DetailedHistory, name='detailed-history'),
    path('report-question/<str:id>/added', views.DisplayReportedQuestion, name='report-question-added'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='FindAccount.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetView.as_view(template_name='ResetPasswordSent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='NewPassword.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='RecoverPasswordComplete.html'), name='password_reset_complete'),
]
